#logging:
#  level:
#    org.springframework.security: INFO
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://auth-service:5000/uaa/users/current
#
#spring:
#  rabbitmq:
#    host: rabbitmq