spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/abc?characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: e3mall-content-service
  redis:
    database: 0
    host: 192.168.25.128
    port: 6379
    password: 
    


#fdfs: 
#  soTimeout: 1500
#  connectTimeout: 600
#  trackerList: 192.168.25.133:22122   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8086
  
#PICTURE-SERVER: 
#  URL: http://192.168.25.133/
  
#内容列表在缓存的key
CONTENT_LIST:
  CONTENT_LIST_NAME: LUNBO_CONTENT
 







