spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/abc?characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:8890
  sleuth:
    sampler:
      percentage: 1.0   
  application:
    name: e3mall-contentCat-service


fdfs: 
  soTimeout: 1500
  connectTimeout: 600
  trackerList: 192.168.25.133:22122   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083
  
PICTURE-SERVER: 
  URL: http://192.168.25.133/
  

 







