spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/abc?characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: e3mall-itemCat-service


fdfs: 
  soTimeout: 1500
  connectTimeout: 600
  trackerList: 192.168.25.133:22122   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8084
  
PICTURE-SERVER: 
  URL: http://192.168.25.133/
  

 







