spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/abc?characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: e3mall-cart-service
  redis:
    database: 0
    host: 192.168.25.128
    port: 6379
    password: 

 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8091
  

  

 







